# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-25 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AlterField(
            model_name='offers',
            name='offer_pre_text',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое описание'),
        ),
    ]
