# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-26 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_reviews_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='tag_priority',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tags',
            name='tag_publish',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
