# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-27 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20170627_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='number',
        ),
        migrations.AlterField(
            model_name='reviews',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
