# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-19 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20170627_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='images_file',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='images',
            name='images_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
