# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-20 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20171219_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offers',
            name='offer_photo_url',
        ),
        migrations.AddField(
            model_name='images',
            name='offer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pages.Offers'),
            preserve_default=False,
        ),
    ]
