# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-20 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20171220_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='main',
            field=models.BooleanField(default=True),
        ),
    ]
