# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-20 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_images_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='max_height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='images',
            name='max_width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='images',
            name='main',
            field=models.BooleanField(default=False),
        ),
    ]
