# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-15 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_auto_20171220_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='images_file',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
