# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-18 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_auto_20180118_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='company',
            name='facebook_link',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
