# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-01 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_auto_20180201_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='offer_article',
            field=models.CharField(blank=True, max_length=50, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='offers',
            name='offer_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='Код товара в вашем каталоге'),
        ),
        migrations.AlterField(
            model_name='offers',
            name='offer_id_on_site',
            field=models.IntegerField(blank=True, verbose_name='ID товара на сайте www.pulscen.ru'),
        ),
    ]
