# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-03 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_auto_20180201_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_priority',
            field=models.IntegerField(default=1),
        ),
    ]
