# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-08 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_post_post_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
