# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-09 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_auto_20180208_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='delete',
            field=models.BooleanField(default=False),
        ),
    ]
