# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-09 08:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_tags_delete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tags',
            old_name='delete',
            new_name='delete_tag',
        ),
    ]
