# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-09 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_auto_20180209_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtags',
            name='delete_stag',
            field=models.BooleanField(default=False),
        ),
    ]
