# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-14 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0027_offers_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtags',
            name='tag_priority',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
