# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-05 11:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0028_subtags_tag_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subtags',
            options={'ordering': ['tag_title'], 'verbose_name': 'Дополнительные теги', 'verbose_name_plural': 'Дополнительные теги'},
        ),
    ]
