# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-13 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0029_auto_20180305_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtags',
            name='tag_description',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
