# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-30 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0031_auto_20180417_0643'),
    ]

    operations = [
        migrations.AddField(
            model_name='fblocks',
            name='fb_color',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='lblocks',
            name='lb_color',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
